# *** Choice state ***
# A Choice state  adds branching logic to a state machine. 
# In addition to most of the common state fields, Choice states contain the following additional fields:
# 1. Choices (Required) - an array of Choice Rules that determines which state the state machine transitions to next.
# 2. Default (Optional, Recommended) - the name of the state to transition to if none of the transitions in Choices is taken.

# *** Map state ***
# The Map state  can run a set of parallel steps for each element of an input array. 
# To configure a Map state, you define an Iterator, which is a complete child workflow execution. 
# When a Step Functions execution enters a Map state, it will iterate over a JSON array in the state input. 
# For each item, the Map state will execute one child workflow execution, potentially in parallel. 
# When all child workflow execution executions complete, the Map state will return an array containing the output for each item processed by the Iterator.

# This module demonstrates dynamic parallelism using the Map and Choice states. It contains the following resources:
# 1. One Amazon DynamoDB table
# 2. One AWS Step Functions state machine

# In this module, you'll pass in a JSON array of orders to be processed by your state machine. 
# A Map state is used to iterate over the input array, similar to a loop in programming languages. 
# In each iteration, the map state dynamically creates separate workflow branches. 
# A choice state is used to determine what action to take for that item in the JSON array, similar to an if statement in programming languages. 
# If the current item's priority field has a value "HIGH", Step Functions writes the order details into DynamoDB. 
# If the current item's priority field is "LOW", no action is taken.

# modify the concurrency limit in template or using the Workflow studion to increase the number of data set processed at the same time


AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Step Functions sample project for mapping over an array of elements
Resources:
  MapStateStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      DefinitionString: |-
          {
            "Comment": "A description of my state machine",
            "StartAt": "Iterate Over Input Array",
            "States": {
              "Iterate Over Input Array": {
                "Type": "Map",
                "ItemProcessor": {
                  "ProcessorConfig": {
                    "Mode": "INLINE"
                  },
                  "StartAt": "Priority Filter",
                  "States": {
                    "Priority Filter": {
                      "Type": "Choice",
                      "Choices": [
                        {
                          "Variable": "$.priority",
                          "StringEquals": "LOW",
                          "Next": "Low Priority Order Detected"
                        },
                        {
                          "Variable": "$.priority",
                          "StringEquals": "HIGH",
                          "Next": "Insert High Priority Order"
                        }
                      ]
                    },
                    "Low Priority Order Detected": {
                      "Type": "Succeed"
                    },
                    "Insert High Priority Order": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::dynamodb:putItem",
                      "Parameters": {
                        "TableName": "MapStateTable",
                        "Item": {
                          "id": {
                            "S.$": "$.orderId"
                          },
                          "customerId": {
                            "S.$": "$.customerId"
                          },
                          "priority": {
                            "S.$": "$.priority"
                          }
                        }
                      },
                      "End": true
                    }
                  }
                },
                "End": true,
                "ItemsPath": "$.Data",
                "MaxConcurrency": 1
              }
            }
          }
      RoleArn: !GetAtt [StatesExecutionRole, Arn]
  StatesExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                Resource:
                  - !GetAtt DDBTable.Arn
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      TableName: 'MapStateTable'
Outputs:
  StateMachineArn:
    Value:
      Ref: MapStateStateMachine
  ExecutionInput:
    Description: Sample input to StartExecution.
    Value: '{}'
