AWSTemplateFormatVersion: '2010-09-09'
Description: 'Custom resource to create a AWS Cloud9 for Step Functions workshop'
Resources:
  Cloud9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 60
      Description: 'Online IDE for workshop'
      InstanceType: t3.medium
      Name: 'StepFunctionsWorkshop'
  Cloud9InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: 'stepfunctionsworkshop-cloud9-role'
      Path: /
      Roles:
        - !Ref AdminRole
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'stepfunctionsworkshop-cloud9-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
